spring:
  profiles:
    default: local
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/sampleapi
      username: sa
      password: ' '
  mvc:
    throw-exception-if-no-handler-found: true

server:
  port: 8080
  shutdown: graceful
  tomcat:
    connection-timeout: 30000

logging:
  config: classpath:log4j2.xml